print (" welcome to code lab")
print ("what's your name")
name= input(" enter name: ")
print(name)
print("what's your age ")
age= input ("enter age:")
print(age)
print("what's your uni")
uni=input("enter uni:")
print(" waht's your country ")
country=input ("enter country:")
print(country)